### ISSUE TITLE
"Show dashboard" doesn't work

### ISSUE THREAD

**Issue by zerofang** [nirdizati/nirdizati-training-backend#8]
Hi! I have successfully trained the model on apromore, and then I followed [this page](http://apromore.org/documentation/features/visualize-performance-predictions-via-dashboard/) to make predictions. However, after I clicked "Show dashboard", it didn't seem to work. As follows:
![QQ截图20200503175517](https://user-images.githubusercontent.com/15062929/80912932-2a615a00-8d73-11ea-99ac-66fdfee6c792.png)
This is apromore's log:
![QQ截图20200503175507](https://user-images.githubusercontent.com/15062929/80912988-8c21c400-8d73-11ea-9418-ae9367d91f90.png)
`    [exec] [2020-05-03 17:46:22,272] INFO  PredictiveMonitorsController - Exported 99 log events
     [exec] [2020-05-03 17:46:22,277] INFO  PredictiveMonitorsController - Exported log to sss
     [exec] [2020-05-03 17:46:22,277] INFO  PredictiveMonitorsController - Loaded
     [exec] [2020-05-03 17:50:38,029] INFO  PredictiveMonitorsController - Monitoring
     [exec] [2020-05-03 17:50:38,114] INFO  PredictiveMonitorsController - Monitored
`
I want to know why this problem occurs and how to solve it. Thank you!

**Comment by verenich** [comment]
Hi @zerofang ,

You need to make sure you have the four processes running as explained on[ this page ](https://github.com/nirdizati/nirdizati-training-backend/blob/master/apromore/README.md) and they are configured correctly (e..g port numbers match):
* Zookeeper
* Kafka
* Events collator
* Predictor

These need to be launched before you start Apromore.

**Comment by zerofang** [comment]
@verenich Thank you! I did forgot to start kafka and zookeeper. 
But when I have fixed it, there are still some other problems. I'm trying to locate and solve them. If I can't, I will ask you again. Thank you!

**Comment by zerofang** [comment]
@verenich I have solved the problem and run the system successfully!
I fixed some bugs that may be related to the new pandas version(pandas1.0.1). I will open another issue and submit a pull request, then you can review it.
nirdizati-training-backend is an amazing work, thank you again for your help!
